[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["themes/**", "Dockerfile", "railway.toml"]

[deploy]
startCommand = "/opt/keycloak/bin/kc.sh start --optimized"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
